### PR TITLE
Prototype: Compagny token in playerboard + Highlight

### PR DESCRIPTION
**Pull request by JohnOrigan**
* Prototype only, just to test the idea
* In image we see "normal" VS "operation phase highlight"
* image

### CODE REVIEW

**Comment by ggohierroy** [comment]
Interesting idea. What does it look like when a player has all 8 companies?

1) They should be in their own row below money and partners.
2) By doing this, we should go further and show all companies in which the player has shares
3) Also show percent ownership for each company and if they're president
4) Add something that will show other players when someone has sold shares in an owned company during the stock round

I'm not saying this should all be implemented in this pull request, but at least have a visual prototype of where we're going with all this.

This way we can also tackle this at the same time: https://boardgamearena.com/bug?id=23016

**Comment by JohnOrigan** [comment]
* Yeah we have to found the right amount of information to display..
* image

**Comment by ggohierroy** [comment]
The percentage can probably be in another row as well with smaller text. You're getting somewhere!

**Comment by ggohierroy** [comment]
I'm not going to merge this one until the game is out of beta. I don't want to risk any instabilities anymore. The focus should be bugs and stability. Thanks!

**Pull request closed without merging**
